from chartMaker import make_chart
from newPrices import make_new_prices

# TEST THEM IF YOU WANT TO..............
# THIS IS JUST A SIMPLE CODE FOR CHANGING VALUES IN EXCEL......

# make_new_prices('transactions.xlsx', 0.8)
# make_chart('transactions.xlsx')

# TEST THEM IF YOU WANT TO..............
# THIS IS JUST A SIMPLE CODE FOR CHANGING VALUES IN EXCEL......

